from pathlib import Path
import json, urllib.parse, urllib.request, xml.etree.ElementTree as ET
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / 'data/dashboard-data.json'

QUERIES = {
 'material-handling':'warehouse automation intralogistics ASRS AMR supply chain logistics',
 'process':'process automation instrumentation chemicals energy pharmaceutical water cybersecurity',
 'heavy-industries':'mining metals cement aggregates critical minerals automation',
 'manufacturing-assembly':'manufacturing automation industrial robotics machine vision assembly reshoring',
 'packaging':'packaging machinery PMMI packaging robotics CPG end-of-line',
 'converting-printing-web':'web handling roll-to-roll converting printing coating laminating winding'
}

MODELS = {
'material-handling': {
 'themes':[('Mixed-fleet orchestration',['orchestration','fleet','amr','mobile robot']),('Scalable warehouse robotics',['robot','as/rs','asrs','automation']),('Modular material-flow architecture',['modular','conveyor','material flow']),('Lifecycle and software support',['software','lifecycle','maintenance','service'])],
 'summary':"Warehouse and intralogistics demand is being shaped by fulfillment volumes, labor availability, network redesign and the cost of capital. {signal} Investment remains strongest where modular automation can improve throughput, space utilization and service levels without creating excessive integration risk.",
 'brief':["Material handling customers are balancing renewed automation demand with disciplined project approval. E-commerce, reshoring, production logistics and persistent labor constraints support investment, while interest rates, tariffs and steel or aluminum costs influence timing and scope.","The strategic shift is from buying isolated equipment to building an integrated material-flow operating system. Conveyors, AS/RS, robotics, AMRs, controls and warehouse software must share diagnostics, data and lifecycle accountability.","OEMs and integrators are best positioned when they can phase deployment, prove operational value early and scale a common architecture across sites."],
 'outlook': [('Base case','Brownfield warehouse automation, controls modernization and phased robotics continue, with customers favoring modular deployments tied to throughput and labor outcomes.'),('Upside','Lower financing friction, reshoring and stronger retail or logistics volumes accelerate greenfield distribution centers and multi-site programs.'),('Downside','Tariffs, construction costs or weaker consumer demand defer large systems, while retrofit, software, service and productivity projects remain active.')],
 'economics':"Global material handling economics are influenced by consumer demand, e-commerce volumes, manufacturing reshoring, warehouse construction, interest rates and equipment input costs. North American reindustrialization and foreign direct investment support production logistics; European demand is more sensitive to slower growth and financing; Asian markets benefit from manufacturing scale and automation adoption. Tariffs and steel or aluminum prices can raise system costs, while lower rates can unlock deferred projects. The OEM implication is to emphasize phased capex, space and labor productivity, integration risk reduction and lifecycle service.",
 'opps':[('Mixed-fleet orchestration','Coordinate AMRs, conveyors, AS/RS, robotics and warehouse software around shared operational priorities.'),('Modular material-flow architecture','Use repeatable machine and controls modules to support phased expansion and engineering reuse.'),('Brownfield modernization','Upgrade installed conveyors, controls, safety and data without requiring total facility replacement.'),('Lifecycle services','Build recurring value around diagnostics, cybersecurity, obsolescence and system performance.')],
 'takeaway':'Position the OEM ecosystem around scalable, connected and supportable material-flow automation. Lead with throughput, labor, space utilization and uptime, then use robotics, software and AI as enablers of those outcomes.'
},
'process': {
 'themes':[('Brownfield control modernization',['brownfield','modernization','migration','dcs']),('Industrial AI in process context',['industrial ai','analytics','artificial intelligence']),('OT cybersecurity and compliance',['cyber','security','62443','compliance']),('Reliability and operator knowledge',['reliability','operator','workforce','maintenance'])],
 'summary':"Process investment is being shaped by energy and feedstock costs, global overcapacity, regulation and the operational risk of changing live plants. {signal} Spending favors secure, phased modernization that protects safety, quality and production continuity.",
 'brief':["Process industries face uneven global conditions. Chemicals are contending with soft demand, overcapacity and regional energy-cost differences, while food, pharmaceuticals, water, LNG and utilities create more resilient pockets of demand.","Customers are modernizing aging controls and connected assets, but shutdown windows, validation requirements and cyber risk constrain the pace. Industrial AI gains credibility when tied to process context, reliability, quality or energy performance.","OEM differentiation comes from secure migration, standardized skids, useful diagnostics and lifecycle support that reduces startup and production risk."],
 'outlook':[('Base case','Producers continue phased control migration, cybersecurity, reliability and energy projects during planned outages.'),('Upside','Improved end-market demand and energy economics accelerate debottlenecking, new process modules and connected asset programs.'),('Downside','Commodity overcapacity and trade disruption delay capacity projects, while safety, compliance, cybersecurity and obsolescence work remain difficult to defer.')],
 'economics':"Global process economics diverge sharply by region and end market. Chemicals face overcapacity, soft commodity demand and high European energy costs; North America benefits from advantaged energy and LNG investment; Asia remains central to capacity and trade flows. Pharmaceuticals and food are comparatively defensive, while oil, gas and chemicals remain exposed to feedstock prices, geopolitics and trade barriers. Environmental regulation, water scarcity and grid investment create additional demand. OEMs should lead with secure brownfield migration, energy efficiency, reliability and flexible skid architectures rather than assuming broad capacity growth.",
 'opps':[('Secure control migration','Modernize aging DCS and PLC assets while protecting production continuity and cybersecurity.'),('Connected asset performance','Combine process, condition and maintenance context around critical equipment.'),('Standardized skid architecture','Deliver reusable modules with consistent controls, networks, security and diagnostics.'),('Operator enablement','Use guided workflows, simulation and remote expertise to preserve process knowledge.')],
 'takeaway':'Lead with low-risk modernization that protects production continuity. Connect secure controls, process expertise and lifecycle support to measurable improvements in reliability, quality, energy performance and regulatory confidence.'
},
'heavy-industries': {
 'themes':[('Critical-mineral supply security',['critical mineral','copper','lithium','rare earth']),('Autonomous and remote operations',['autonomous','remote','automation']),('Energy and cost per ton',['energy','cost','ore grade','productivity']),('Reliability and outage execution',['reliability','maintenance','outage','uptime'])],
 'summary':"Heavy-industry demand is tied to commodity prices, infrastructure, critical-mineral policy, Chinese demand and energy costs. {signal} Long-term supply-security needs support investment, but commodity volatility and long project cycles favor reliability and brownfield work.",
 'brief':["Mining, metals, cement and bulk-processing markets are supported by infrastructure, electrification and regional supply-security priorities, but the opportunity is uneven by commodity and geography.","Higher energy costs, declining ore grades, permitting requirements and capital intensity increase the value of automation that improves recovery, throughput, safety and maintenance effectiveness.","Brownfield debottlenecking, autonomous operations and outage-based modernization generally offer more resilient conversion than broad greenfield capacity."],
 'outlook':[('Base case','Reliability, debottlenecking, energy efficiency and planned-outage work outpace broad new-capacity investment.'),('Upside','Critical-mineral policy, infrastructure spending and stronger commodity prices accelerate mines, processing plants and metals capacity.'),('Downside','Chinese weakness, oversupply or financing pressure delays greenfield projects, while critical-asset and maintenance programs continue.')],
 'economics':"Global heavy-industry economics are driven by commodity prices, Chinese construction and manufacturing demand, infrastructure spending, energy costs, exchange rates and critical-mineral policy. Copper and selected critical minerals benefit from electrification and supply-security investment, while lithium, nickel, iron ore or other markets may face oversupply. Inflation, lower ore grades and energy intensity raise cost per ton. Permitting and geopolitical regionalization lengthen project cycles but also support domestic capacity. OEMs should quantify uptime, recovery, energy per ton and outage execution rather than relying on a generic growth narrative.",
 'opps':[('Autonomous and remote operations','Improve safety, consistency and access to scarce operating expertise.'),('Critical-asset reliability','Prioritize conveyors, crushers, mills, kilns, pumps and other production constraints.'),('Energy and power optimization','Reduce energy per ton and coordinate production with power availability and cost.'),('Outage-based modernization','Stage controls, drives and network migrations within planned shutdown windows.')],
 'takeaway':'Prioritize reliability, safety and production economics. Position automation around reduced downtime, energy per ton, autonomous operations and staged modernization completed within planned outages.'
},
'manufacturing-assembly': {
 'themes':[('Flexible robotics for product mix',['flexible','robot','cobot','high mix']),('Vision, quality and traceability',['vision','quality','inspection','traceability']),('Digital engineering and launch speed',['digital twin','simulation','commissioning']),('Reshoring and workforce capacity',['reshoring','workforce','labor','skills'])],
 'summary':"Discrete manufacturing is being shaped by industrial production, machinery orders, automotive and aerospace cycles, reshoring and labor availability. {signal} Flexible robotics, vision and digital engineering remain attractive where they improve quality and product-mix agility.",
 'brief':["Manufacturing and assembly investment benefits from reindustrialization, aerospace demand, electronics and selected automotive programs, but end-market cycles and tariffs create uneven conditions.","Customers increasingly favor reusable cells and machine architectures that can support multiple products, faster launches and future expansion. Robotics, vision, motion, safety and production data are converging.","The strongest business cases connect automation to quality, utilization, engineering reuse, labor capacity and commissioning speed."],
 'outlook':[('Base case','Flexible robotics, vision and digital-engineering projects continue around labor, quality and product-mix requirements.'),('Upside','Reshoring, aerospace growth and factory expansion accelerate reusable cells, new lines and capacity programs.'),('Downside','Automotive or machinery weakness slows capacity projects, while quality automation, engineering reuse and targeted labor-saving work persist.')],
 'economics':"Global discrete-manufacturing economics depend on industrial production, machinery orders, automotive and aerospace build rates, electronics cycles, trade policy and foreign direct investment. North American reshoring and defense or aerospace demand support new capacity; European manufacturers face energy and competitiveness pressure; Asian supply chains remain central to electronics and machinery. Tariffs can encourage localization but also raise component and equipment costs. Higher wages and scarce controls or maintenance skills support automation. OEMs should emphasize flexible capacity, engineering reuse, quality and faster launch rather than fixed high-volume assumptions.",
 'opps':[('Flexible robotic cells','Support mixed-model assembly, tending, material movement and inspection with reusable designs.'),('Integrated motion, safety and vision','Simplify high-performance architectures and improve machine-level quality.'),('Digital engineering','Use simulation, emulation and reusable code to reduce design and commissioning time.'),('Quality and traceability','Connect inspection, genealogy and production context across the line.')],
 'takeaway':'Connect flexible automation to product-mix agility, quality and launch speed. Emphasize reusable machine architectures, integrated robotics and vision, and digital engineering that reduces commissioning time and engineering effort.'
},
'packaging': {
 'themes':[('Flexible machinery and changeover',['changeover','flexible','sku']),('End-of-line robotics and AMRs',['pallet','robot','amr','end-of-line']),('Obsolescence and aftermarket growth',['obsolescence','lifecycle','service']),('Material and EPR adaptation',['recycl','epr','material','sustainability'])],
 'summary':"Packaging demand is influenced by consumer volumes, food and beverage, pharmaceuticals, materials regulation and machinery sourcing. {signal} Flexibility, robotics and lifecycle services remain important as SKU complexity and changing package formats reshape investment.",
 'brief':["Packaging machinery benefits from relatively defensive food, beverage, pharmaceutical and consumer-goods demand, yet customers face volatile volumes, trade costs and changing package materials.","The value equation is shifting from peak rated speed toward mix-adjusted throughput, rapid changeover, ease of operation and lifecycle resilience.","End-of-line robotics, modular machine architecture, obsolescence planning and material flexibility create differentiated OEM opportunities."],
 'outlook':[('Base case','Flexible machinery, changeover improvement, end-of-line automation and lifecycle programs support steady demand.'),('Upside','CPG capacity, pharmaceutical investment and package-format changes accelerate new machinery and line modernization.'),('Downside','Consumer weakness or tariff-driven equipment costs slow new lines, while aftermarket, obsolescence and targeted robotics remain resilient.')],
 'economics':"Global packaging economics are tied to food, beverage, pharmaceutical and consumer-goods volumes, as well as resin, paper, aluminum and energy costs. Demand is comparatively defensive, but regional consumer softness and private-label shifts affect product mix. Tariffs and exchange rates influence imported machinery and components. Material-reduction rules, recycled-content requirements and extended producer responsibility change machine specifications across North America and Europe. Emerging-market consumption supports long-term growth. OEMs should emphasize rapid changeover, material flexibility, total cost of ownership and aftermarket support.",
 'opps':[('Modular machine architecture','Standardize controls, motion, safety and data for reuse across machine families.'),('Rapid changeover and recipes','Reduce setup losses and support broader SKU portfolios.'),('End-of-line robotics','Integrate palletizing, case handling, mobile movement and load stabilization.'),('Obsolescence and aftermarket services','Use installed-base visibility, conversion kits and proactive lifecycle planning.')],
 'takeaway':'Lead with flexible, operator-friendly packaging systems rather than maximum machine speed alone. Differentiate through rapid changeover, modular architecture, end-of-line integration and proactive lifecycle support.'
},
'converting-printing-web': {
 'themes':[('Precision web control',['tension','registration','web handling']),('Inline inspection and waste reduction',['inspection','waste','yield','quality']),('Workflow and recipe integration',['workflow','recipe','digital']),('New substrates and coatings',['substrate','coating','laminating','battery'])],
 'summary':"Converting and print demand is shaped by packaging volumes, commercial print, substrate costs, run-length compression and specialty roll-to-roll applications. {signal} Precision control and inspection remain defensible because waste and setup directly affect margin.",
 'brief':["Converting, printing and web-processing markets face shorter runs, customization, substrate variability and pressure to reduce startup waste. Packaging and specialty applications are generally more resilient than traditional commercial print.","Tension, registration, coating, winding and inspection performance have direct economic value because small process variations can create costly material loss.","Digital workflow integration and flexible controls help converters manage job complexity, preserve know-how and adapt to emerging roll-to-roll applications."],
 'outlook':[('Base case','Web control, inspection and workflow automation improve yield and support shorter production runs.'),('Upside','Flexible packaging, specialty coatings, batteries and advanced roll-to-roll applications expand equipment demand.'),('Downside','Weak print volumes or high substrate costs slow capacity spending, while waste reduction and precision upgrades remain defensible.')],
 'economics':"Global CPW economics vary by application. Packaging, labels and specialty coatings remain more resilient than commercial print, while advertising and publishing are sensitive to economic growth. Resin, film, foil, paper, ink and energy prices directly affect margins because substrate waste is costly. Shorter runs increase setup frequency and favor automation. Currency and trade conditions shape machinery exports, while sustainability rules accelerate mono-material structures and new coatings. Battery electrodes and flexible electronics create high-value roll-to-roll opportunities. OEMs should quantify yield, startup waste, registration and changeover performance.",
 'opps':[('Precision web control','Coordinate speed, tension, registration and winding across the full web path.'),('Inline inspection and analytics','Connect quality findings to process conditions and corrective action.'),('Recipe and workflow integration','Link job data, setup parameters, quality records and downstream finishing.'),('Controls and drive modernization','Upgrade aging platforms during planned maintenance while preserving process knowledge.')],
 'takeaway':'Position precision as a measurable business outcome. Lead with tension and registration control, inline quality, reduced startup waste and connected workflows that improve yield across complex substrates and applications.'
}}

POS=['growth','expand','increase','investment','record','demand','adoption','recovery','strong','accelerat','opportunity','resilien','productivity']
NEG=['decline','slow','risk','shortage','tariff','cost','uncertain','layoff','weak','pressure','delay','volatile','overcapacity']
TECH=['automation','robot','ai ','digital','software','vision','autonomous','analytics']
CAP=['investment','order','project','capacity','plant','facility','capital']
WORK=['labor','workforce','skills','hiring','operator','talent']

def hits(t,w): return sum(t.count(x) for x in w)
def clamp(x,a=0,b=100): return max(a,min(b,int(round(x))))
def sentiment_label(s): return 'Strongly positive' if s>=85 else 'Positive' if s>=75 else 'Constructive' if s>=65 else 'Selectively constructive' if s>=55 else 'Mixed' if s>=45 else 'Cautious' if s>=30 else 'Negative'
def fetch(q):
 u='https://news.google.com/rss/search?q='+urllib.parse.quote(q)+'&hl=en-US&gl=US&ceid=US:en'
 req=urllib.request.Request(u,headers={'User-Agent':'Mozilla/5.0 OEM-Intelligence-Dashboard/2.0'})
 with urllib.request.urlopen(req,timeout=30) as response: root=ET.fromstring(response.read())
 out=[]
 for item in root.findall('.//item')[:20]:
  title=item.findtext('title','').strip(); url=item.findtext('link','').strip(); pub=item.findtext('pubDate','').strip(); source=item.findtext('source','').strip()
  if title and url: out.append({'title':title,'url':url,'published':pub,'source':source or 'Google News'})
 return out

def update_segment(slug,s,news,now):
 m=MODELS[slug]; text=' '.join(x['title'].lower() for x in news)
 pos=hits(text,POS); neg=hits(text,NEG); total=max(pos+neg,1)
 demand=clamp(50+30*(pos-neg)/total,25,90); tech=clamp(42+5*hits(text,TECH),25,92); capital=clamp(46+6*hits(text,CAP)-3*hits(text,['tariff','uncertain','delay']),25,90); workforce=clamp(70-7*hits(text,WORK),20,80)
 prior=s.get('score',65); raw=.34*demand+.24*tech+.22*capital+.10*workforce+.10*prior; score=clamp(max(prior-5,min(prior+5,raw)),25,95)
 posture='accelerating' if score>=80 else 'disciplined' if score>=65 else 'selective' if score>=50 else 'cautious'
 signal=f"The current evidence set is {sentiment_label(score).lower()} at {score}, with {('growth signals outweighing constraints' if pos>=neg else 'constraints tempering otherwise durable automation needs')} and a {posture} capital posture."
 ranked=sorted(((hits(text,words),name) for name,words in m['themes']),reverse=True); leaders=[name for _,name in ranked]
 s.update({'score':score,'label':sentiment_label(score),'summary':m['summary'].format(signal=signal),'leaders':leaders,'brief':[m['brief'][0]+' '+signal,m['brief'][1],m['brief'][2]],'outlook':[{'case':a,'text':b} for a,b in m['outlook']],'economics':m['economics']+f" Current headline evidence includes {pos} positive-growth references and {neg} constraint references across {len(news)} selected items; capital confidence calculates to {capital}.",'opportunities':[{'title':a,'text':b} for a,b in m['opps']],'executive_takeaway':m['takeaway'],'news':news[:5]})
 s['drivers']=[{'name':'Market demand','score':demand},{'name':'Technology adoption','score':tech},{'name':'Capital confidence','score':capital},{'name':'Workforce availability','score':workforce},{'name':'External risk clarity','score':clamp(65-5*neg,20,80)},{'name':'Strategic resilience','score':clamp(62+4*hits(text,['resilien','regional','secure','lifecycle']),40,90)}]
 s['metrics']=[{'label':'Composite sentiment','value':str(score),'note':s['label']},{'label':'Articles analyzed','value':str(len(news)),'note':'Current monthly evidence set'},{'label':'Headline signal mix','value':f'{round(100*pos/total)}% positive','note':f'{pos} positive · {neg} constraint references'},{'label':'Technology signal','value':str(tech),'note':'Rules-based evidence score'},{'label':'Investment posture','value':posture.title(),'note':now.strftime('%B %Y')}]
 s['automation_note']='Automatically refreshed from public headline metadata using segment-specific rules and economic context. Review before external distribution.'

data=json.loads(DATA_PATH.read_text(encoding='utf-8')); now=datetime.now(timezone.utc); success=0
for slug,q in QUERIES.items():
 try:
  articles=fetch(q)
  if not articles: raise RuntimeError('No articles returned')
  update_segment(slug,data['segments'][slug],articles,now); success+=1
 except Exception as exc: print(f'WARNING {slug}: {exc}; retaining last successful content')
if success: data['last_refreshed']=now.isoformat().replace('+00:00','Z')
data['refresh_scope']='Segment-specific monthly refresh of summaries, drivers, briefs, outlooks, economics, opportunities and newsroom.'
DATA_PATH.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print(f'Refreshed {success} of {len(QUERIES)} segments')
