from pathlib import Path
import json, urllib.parse, urllib.request, xml.etree.ElementTree as ET
from datetime import datetime, timezone
ROOT=Path(__file__).resolve().parents[1]; P=ROOT/'data/dashboard-data.json'
Q={'material-handling':'warehouse automation OR intralogistics OR ASRS OR AMR','process':'process automation OR instrumentation OR DCS industrial','heavy-industries':'mining automation OR metals industry OR cement automation','manufacturing-assembly':'manufacturing automation OR industrial robotics OR machine vision','packaging':'packaging machinery OR PMMI OR packaging robotics','converting-printing-web':'web handling OR roll-to-roll converting OR printing automation'}
GUIDANCE={
'material-handling':{'context':'Customers are evaluating complete material-flow systems rather than isolated equipment.','focus':'mixed-fleet orchestration, modular material-flow architecture, brownfield modernization and lifecycle services','takeaway':'Position the OEM ecosystem around scalable, connected and supportable material-flow automation. Lead with throughput, labor, space utilization and uptime, then use robotics, software and AI as enablers of those outcomes.'},
'process':{'context':'Customers must modernize aging process assets without compromising safety, quality or production continuity.','focus':'secure brownfield migration, interoperable skid architecture, asset performance and operator enablement','takeaway':'Lead with low-risk modernization that protects production continuity. Connect secure controls, process expertise and lifecycle support to measurable improvements in reliability, quality, energy performance and regulatory confidence.'},
'heavy-industries':{'context':'Operators are balancing critical-material demand with commodity volatility, energy intensity and complex project economics.','focus':'asset reliability, autonomous operations, energy optimization and outage-based modernization','takeaway':'Prioritize reliability, safety and production economics. Position automation around reduced downtime, energy per ton, autonomous operations and staged modernization completed within planned outages.'},
'manufacturing-assembly':{'context':'Manufacturers need flexible capacity that can absorb product variation, labor constraints and faster launch cycles.','focus':'flexible robotic cells, integrated motion and safety, machine vision, traceability and digital engineering','takeaway':'Connect flexible automation to product-mix agility, quality and launch speed. Emphasize reusable machine architectures, integrated robotics and vision, and digital engineering that reduces commissioning time and engineering effort.'},
'packaging':{'context':'Packaging operations are managing SKU growth, shorter runs, workforce turnover, changing materials and lifecycle risk.','focus':'modular machinery, rapid changeover, end-of-line automation, obsolescence planning and aftermarket services','takeaway':'Lead with flexible, operator-friendly packaging systems rather than maximum machine speed alone. Differentiate through rapid changeover, modular architecture, end-of-line integration and proactive lifecycle support.'},
'converting-printing-web':{'context':'Converters are managing shorter runs, expensive substrates, tighter process windows and pressure to reduce startup waste.','focus':'precision web control, inline inspection, recipe integration, workflow automation and lifecycle modernization','takeaway':'Position precision as a measurable business outcome. Lead with tension and registration control, inline quality, reduced startup waste and connected workflows that improve yield across complex substrates and applications.'}}
POS=['growth','expand','increase','investment','record','demand','adoption','recovery','strong','accelerat','opportunity','resilien','productivity'];NEG=['decline','slow','risk','shortage','tariff','cost','uncertain','layoff','weak','pressure','delay','volatile'];TECH=['automation','robot','ai ','digital','software','vision','autonomous','analytics'];CAP=['investment','order','project','capacity','plant','facility','capital'];WORK=['labor','workforce','skills','hiring','operator','talent']
def hits(t,w):return sum(t.count(x) for x in w)
def clamp(x,a=0,b=100):return max(a,min(b,int(round(x))))
def label(s):return 'Strongly positive' if s>=85 else 'Positive' if s>=75 else 'Constructive' if s>=65 else 'Selectively constructive' if s>=55 else 'Mixed' if s>=45 else 'Cautious' if s>=30 else 'Negative'
def fetch(q):
 u='https://news.google.com/rss/search?q='+urllib.parse.quote(q)+'&hl=en-US&gl=US&ceid=US:en';r=urllib.request.Request(u,headers={'User-Agent':'Mozilla/5.0 OEM-Intelligence-Dashboard/1.0'})
 with urllib.request.urlopen(r,timeout=30) as x:root=ET.fromstring(x.read())
 out=[]
 for i in root.findall('.//item')[:20]:
  title=i.findtext('title','').strip();url=i.findtext('link','').strip();pub=i.findtext('pubDate','').strip();source=i.findtext('source','').strip()
  if title and url:out.append({'title':title,'url':url,'published':pub,'source':source or 'Google News'})
 return out
def derive(slug,s,news,now):
 t=' '.join(x['title'].lower() for x in news);pos=hits(t,POS);neg=hits(t,NEG);total=max(pos+neg,1);tone=50+30*(pos-neg)/total;tech=clamp(45+5*hits(t,TECH),25,95);capital=clamp(45+6*hits(t,CAP)+.15*(tone-50),25,95);work=clamp(70-7*hits(t,WORK),20,80);prior=s.get('score',65);score=clamp(max(prior-5,min(prior+5,.32*tone+.24*tech+.22*capital+.12*work+.10*prior)),25,95);posture='Accelerating' if score>=80 else 'Disciplined' if score>=65 else 'Selective' if score>=50 else 'Cautious';g=GUIDANCE[slug]
 s['score']=score;s['label']=label(score);s['news']=news[:5];s['executive_takeaway']=g['takeaway'];s['summary']=f"The {s['name']} signal is {s['label'].lower()} at {score}. Current evidence shows {'more growth and investment signals than constraints' if pos>=neg else 'meaningful cost and execution constraints alongside opportunity'}. Technology adoption remains {'strong' if tech>=70 else 'selective'}, while capital conversion remains {posture.lower()}."
 s['metrics']=[{'label':'Composite sentiment','value':str(score),'note':s['label']},{'label':'Articles analyzed','value':str(len(news)),'note':'Current monthly evidence set'},{'label':'Positive signal share','value':f'{round(100*pos/total)}%','note':'Headline-language indicator'},{'label':'Technology signal','value':str(tech),'note':'Rules-based evidence score'},{'label':'Investment posture','value':posture,'note':now.strftime('%B %Y')}]
 s['drivers']=[{'name':'Market demand','score':clamp(tone)},{'name':'Technology adoption','score':tech},{'name':'Capital confidence','score':capital},{'name':'Workforce availability','score':work},{'name':'External risk clarity','score':clamp(62-5*neg,20,80)},{'name':'Strategic resilience','score':clamp(60+4*hits(t,['resilien','regional','secure','lifecycle']),40,90)}]
 s['brief']=[f"The monthly evidence set places {s['name']} at a {s['label'].lower()} composite score of {score}. {g['context']} The current investment posture remains {posture.lower()}.",f"For {s['name']}, leadership attention points specifically toward {g['focus']}. These priorities translate the current evidence into the operating language and decision criteria of the segment.",f"For OEMs serving this segment, differentiation depends on connecting technology to customer operating measures and providing a clear implementation and lifecycle path."]
 s['outlook']=[{'case':'Base case','text':f"The {s['name']} market remains {s['label'].lower()}, with disciplined conversion around measurable outcomes."},{'case':'Upside','text':'Improving demand and capital confidence accelerate scalable modernization and new capacity.'},{'case':'Downside','text':'Cost, trade or financing pressure delays larger projects while service, retrofit and reliability work remain active.'}]
 s['economics']=f"The current monthly evidence set contains {pos} positive-growth references and {neg} constraint references across {len(news)} selected items. Capital confidence is {capital}, supporting a {posture.lower()} posture. This is directional market intelligence; use the linked ISM and Federal Reserve sources for primary economic data."
 s['opportunities']=[{'title':g['focus'].split(',')[0].title(),'text':'Leading segment-specific priority in the current monthly framework.'},{'title':g['focus'].split(',')[1].strip().title(),'text':'Second segment-specific priority tied to OEM differentiation.'},{'title':'Lifecycle modernization','text':'Use installed-base visibility and migration planning to reduce customer risk.'},{'title':'Scalable architecture','text':'Translate demand into reusable controls, data, safety and application patterns.'}];s['automation_note']='Automatically generated from public headline metadata using transparent rules. Review before external distribution.'
d=json.loads(P.read_text());now=datetime.now(timezone.utc);ok=0
for slug,q in Q.items():
 try:
  n=fetch(q)
  if not n:raise RuntimeError('No articles returned')
  derive(slug,d['segments'][slug],n,now);ok+=1
 except Exception as e:print('WARNING',slug,e)
if ok:d['last_refreshed']=now.isoformat().replace('+00:00','Z')
P.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');print('Refreshed',ok,'segments')
